### ISSUE TITLE
Request - ASREPRoast

### ISSUE THREAD

**Issue by Lexus89** [skelsec/PyKerberoast#2]
This is my favorite script for kerberoast, would be a great addition to also have an implementation of AsRepRoast with a list/bruteforce of accounts:

http://www.harmj0y.net/blog/activedirectory/roasting-as-reps/

**Comment by skelsec** [comment]
Thank you for your kind words, however this script is obsoleted by [kerberoast package](https://github.com/skelsec/kerberoast) which can do a lot more in a better fashion as this (eg doesnt require impacket) and support CCACHE and mimikatz's kirbi files.

With that being said, I'll consider adding ASREPRoast in the future when I'm a bit less busy. Maybe this weekend? I dunno.

(edited: wrong URL)

**Comment by skelsec** [comment]
Please submit this issue there.
