### ISSUE TITLE
Error: KRB bad integrity

### ISSUE THREAD

**Issue by Lexus89** [skelsec/PyKerberoast#3]
For some users i receive the following error (verbose error):

WARNING! Failed to get ticket for user hacker Exception data: Kerberos SessionError: KRB_AP_ERR_BAD_INTEGRITY(Integrity check on decrypted field failed)

I read about some protection that might cause this error due to having an invalid session key. Could that be it?

**Comment by skelsec** [comment]
You'd need to send some more data to check, or a way to reproduce it.

**Comment by skelsec** [comment]
Just like for the previous issue, please check if the new package produces the same error, and if so submit an issue there.
